name: flutter_connectivity
description: "Monitors and reports connection quality to a specific server. Ensures real internet access, not just connectivity. Pure Dart, Dart/Flutter compatible."
version: 0.0.3
homepage: https://github.com/dev-kasibhatla/flutter_connectivity
documentation: https://pub.dev/packages/flutter_connectivity
issue_tracker: https://github.com/dev-kasibhatla/flutter_connectivity/issues

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  http: ^1.2.1
  log_plus: ^0.0.6

dev_dependencies:
  test: ^1.6.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
